model: unet_smooth

forward_model: unet_smooth
forward_checkpoint: Forward_Model.pt

loss:
  weights:
    bce: 1
    dice: 1
    mse: 1
    lap: 0.001

base_logits_scale: 1.2
delta_scale: 1.8
sigmoid_scale: 2.0

use_gaussian_blur: True
blur_strength: 2.0

save_every: 2
lr: 0.00001
batch_size: 5
epochs: 50
weight_decay: 0.00001
log_every: 1

data_root: /content/data_ilt/mental_layer_input/png

pattern_types:
  - mental_layer
  - mental_line
  - mental_corner
  - mental_curve
  - mental_head
  - mental_circle

output_root: /content/drive/MyDrive/Colab Notebooks/experiments_ILT
output_dir: exp_ilt_unet_smooth_bce_dice_mse_0.001lap_1.2base_1.8delta_2sigmoid_2blur

device: auto
num_workers: 0
seed: 42

remark: 学习率必须是 1e-5。原有的1e-4会出现异常图像