model: unet_smooth

forward_model: unet_smooth
forward_checkpoint: Forward_Model.pt

loss:
  weights:
    mse: 1

save_every: 1
lr: 0.00001
batch_size: 50
epochs: 30
weight_decay: 0.00001
log_every: 1

data_root: /content/data_ilt/mental_layer_input/png

pattern_types:
  - mental_layer
  - mental_line
  - mental_corner
  - mental_curve
  - mental_head
  - mental_circle

output_root: /content/drive/MyDrive/Colab Notebooks/experiments_ILT
output_dir: exp_ilt_unet_smooth_debug
device: auto
num_workers: 0
seed: 42